// ============================================================================
// RANIA V2.1 — Iron Rules Enforcement
// The 4 Iron Rules from Maun Luis — NON-NEGOTIABLE
// ============================================================================

import type { IronRuleViolation, FlightResult, BookingStatus } from "./types";

// ─── IRON RULE #1: NEVER store credit card numbers or CVV ────────────────────

const CARD_NUMBER_REGEX = /\b(?:\d[ -]*?){13,19}\b/;
const CVV_REGEX = /\b\d{3,4}\b/;

/**
 * Scans a string for potential credit card numbers.
 * Returns a violation if found.
 */
export function scanForCreditCard(data: string, context: string): IronRuleViolation | null {
  // Simple Luhn-like check: 13-19 consecutive digits (with spaces/dashes)
  if (CARD_NUMBER_REGEX.test(data)) {
    return {
      rule: "NO_CREDIT_CARD_STORAGE",
      severity: "BLOCK",
      message: `BLOCKED: Potential credit card number detected in ${context}. Iron Rule #1: NEVER store card numbers.`,
      context,
    };
  }
  return null;
}

/**
 * Validates that no credit card data is being stored in any field.
 * Scans all string values in an object.
 */
export function validateNoCardStorage(obj: Record<string, unknown>, context: string): IronRuleViolation[] {
  const violations: IronRuleViolation[] = [];
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === "string") {
      const v = scanForCreditCard(value, `${context}.${key}`);
      if (v) violations.push(v);
    }
    // Block any field named like card fields
    const lowerKey = key.toLowerCase();
    if (["cardnumber", "card_number", "cvv", "cvc", "ccv", "securitycode", "security_code"].includes(lowerKey)) {
      violations.push({
        rule: "NO_CREDIT_CARD_STORAGE",
        severity: "BLOCK",
        message: `BLOCKED: Field "${key}" looks like credit card data. Iron Rule #1: NEVER store card numbers or CVV.`,
        context: `${context}.${key}`,
      });
    }
  }
  return violations;
}

// ─── IRON RULE #2: NEVER edit airline PDF tickets ────────────────────────────

/**
 * Validates that we're sending 2 separate files:
 * 1. Original e-ticket PDF (untouched from airline)
 * 2. RANIA invoice PDF (our own invoice)
 *
 * NEVER merge, edit, or modify the airline's PDF.
 */
export function validatePdfIntegrity(files: { type: string; source: string }[]): IronRuleViolation[] {
  const violations: IronRuleViolation[] = [];
  const eTickets = files.filter(f => f.type === "e-ticket");
  const invoices = files.filter(f => f.type === "invoice");

  if (eTickets.length === 0) {
    violations.push({
      rule: "NO_PDF_EDITING",
      severity: "WARN",
      message: "WARNING: No e-ticket PDF found. Should send original airline e-ticket.",
    });
  }

  if (invoices.length === 0) {
    violations.push({
      rule: "NO_PDF_EDITING",
      severity: "WARN",
      message: "WARNING: No RANIA invoice PDF found. Should send separate RANIA invoice.",
    });
  }

  // Check that e-ticket comes from airline/travelport, not from our system
  for (const ticket of eTickets) {
    if (ticket.source === "rania" || ticket.source === "edited") {
      violations.push({
        rule: "NO_PDF_EDITING",
        severity: "BLOCK",
        message: "BLOCKED: E-ticket appears to be modified or generated by RANIA. Iron Rule #2: NEVER edit airline PDFs.",
        context: ticket.source,
      });
    }
  }

  return violations;
}

// ─── IRON RULE #3: NEVER auto-refund on error ────────────────────────────────

/**
 * When an error occurs, set status to 'VERIFY' for admin review.
 * NEVER automatically catch(e) → refund().
 * Admin has 5 minutes to review and decide: APPROVE, REJECT, or REFUND.
 */
export function getErrorStatus(): BookingStatus {
  // Always return VERIFY on error — never auto-refund
  return "VERIFY";
}

/**
 * Validates that a refund action is ONLY triggered by admin, never automatically.
 */
export function validateRefundAuthorization(
  actor: string,
  reason?: string
): IronRuleViolation | null {
  if (actor !== "admin") {
    return {
      rule: "NO_AUTO_REFUND",
      severity: "BLOCK",
      message: `BLOCKED: Refund requested by "${actor}" but only admin can trigger refunds. Iron Rule #3: catch(e) → status='VERIFY' → admin review.`,
      context: reason,
    };
  }
  return null;
}

// ─── IRON RULE #4: REAL API ONLY — No static/fallback prices ─────────────────

/**
 * Validates that ALL flight results come from a real API source.
 * Rejects any result that looks like it has hardcoded/static prices.
 */
export function validateRealApiPrices(results: FlightResult[]): IronRuleViolation[] {
  const violations: IronRuleViolation[] = [];
  const validSources: string[] = ["travelport", "trip", "travelpayouts"];

  for (const result of results) {
    // Check source is a real API
    if (!validSources.includes(result.source)) {
      violations.push({
        rule: "NO_STATIC_PRICES",
        severity: "BLOCK",
        message: `BLOCKED: Flight result from unknown source "${result.source}". Only real API sources allowed.`,
        context: result.id,
      });
    }

    // Check that price is a positive number (not zero, not negative)
    if (result.totalPrice <= 0 || !Number.isFinite(result.totalPrice)) {
      violations.push({
        rule: "NO_STATIC_PRICES",
        severity: "BLOCK",
        message: `BLOCKED: Invalid price ${result.totalPrice} for flight ${result.id}. Prices must come from API.`,
        context: result.id,
      });
    }

    // Check lastUpdated is recent (within 24 hours)
    if (result.lastUpdated) {
      const age = Date.now() - new Date(result.lastUpdated).getTime();
      if (age > 86400000) { // 24 hours
        violations.push({
          rule: "NO_STATIC_PRICES",
          severity: "WARN",
          message: `WARNING: Flight price data is ${Math.round(age / 3600000)}h old. Consider refreshing.`,
          context: result.id,
        });
      }
    }
  }

  return violations;
}

/**
 * Checks if a string contains forbidden estimation text.
 * Iron Rule #4: Never output "harga indikasi" or "estimasi" for prices.
 */
export function scanForEstimationText(text: string): IronRuleViolation | null {
  const forbidden = [
    "harga indikasi",
    "harga estimasi",
    "estimated price",
    "indication price",
    "perkiraan harga",
    "harga perkiraan",
    "harga kisaran",
    "approximate price",
  ];

  const lower = text.toLowerCase();
  for (const phrase of forbidden) {
    if (lower.includes(phrase)) {
      return {
        rule: "NO_STATIC_PRICES",
        severity: "BLOCK",
        message: `BLOCKED: Text contains forbidden estimation phrase "${phrase}". Iron Rule #4: All prices must be from real API.`,
        context: text.substring(0, 100),
      };
    }
  }
  return null;
}

// ─── Utility: Run all Iron Rule checks ───────────────────────────────────────

/**
 * Master validator — runs all relevant Iron Rule checks on a booking payload.
 * Returns all violations found. If any BLOCK-level violations exist, the
 * operation MUST be rejected.
 */
export function runAllIronRuleChecks(payload: {
  data?: Record<string, unknown>;
  flightResults?: FlightResult[];
  files?: { type: string; source: string }[];
  responseText?: string;
}): IronRuleViolation[] {
  const violations: IronRuleViolation[] = [];

  // Rule #1: No credit card storage
  if (payload.data) {
    violations.push(...validateNoCardStorage(payload.data, "booking"));
  }

  // Rule #2: No PDF editing
  if (payload.files) {
    violations.push(...validatePdfIntegrity(payload.files));
  }

  // Rule #4: Real API prices only
  if (payload.flightResults) {
    violations.push(...validateRealApiPrices(payload.flightResults));
  }

  // Rule #4: No estimation text
  if (payload.responseText) {
    const v = scanForEstimationText(payload.responseText);
    if (v) violations.push(v);
  }

  return violations;
}

/**
 * Check if any violations should BLOCK the operation.
 */
export function hasBlockingViolations(violations: IronRuleViolation[]): boolean {
  return violations.some(v => v.severity === "BLOCK");
}
